
// md2doc_official.js — uses Theme/Lesson templates; now includes lesson dates/times
async function loadThemeTpl(){ const [h,c]=await Promise.all([fetch('agents/english_agent/templates/theme_planner_template.html'), fetch('agents/english_agent/templates/theme_planner_styles.css')]); return { html: await h.text(), css: await c.text() }; }
async function loadLessonTpl(){ const [h,c]=await Promise.all([fetch('agents/english_agent/templates/lesson_planner_template.html'), fetch('agents/english_agent/templates/lesson_planner_styles.css')]); return { html: await h.text(), css: await c.text() }; }
function fill(html, data){ let out=html; Object.entries(data).forEach(([k,v])=>{ out = out.replaceAll(`{{${k}}}`, v ?? ''); }); return out; }
function blobDoc(html){ return new Blob([html], {type:'application/msword'}); }
function themeData(S){
  const rowsOutcomes = ['Listening','Reading','Speaking','Writing','Mediation'].map(skill=>{ const std=(S.standards?.[skill])||''; const lo=(S.outcomes?.[skill])||''; return `<tr><td>${skill}</td><td>${std}</td><td>${lo}</td></tr>`; }).join('\n');
  const seq = (S.lessonMeta||[]).map((m,i)=>`<tr><td>Lesson ${i+1}</td><td>${m.date||''}</td><td></td></tr>`).join('\n');
  return { Teacher:S.teacher||'', Grade:S.grade||'', CEFR:S.cefr||'', Trimester:S.term||'', WeeklyHours:S.weeklyHours||'', Weeks:S.weeks||'', Scenario:S.scenario||'', Theme:S.theme||'', OutcomesRows:rowsOutcomes, Grammar:(S.grammarList||[]).join(', '), Vocabulary:(S.vocabList||[]).join(', '), Pronunciation:'', Pragmatic:'', Sociolinguistic:'', Project:'Collaborative mini‑poster', Materials:'', DI:'', SequenceRows:seq };
}
function lessonsHtmlFromState(S){ return (S.lessons||[]).map((L,i)=>{ const meta=(S.lessonMeta||[])[i]||{}; const tplVars={ ThemeNo:S.theme||'', LessonNo:(i+1), Grade:S.grade||'', Scenario:S.scenario||'', Theme:S.theme||'', Dates:meta.date||'', LSTime:(meta.time||''), SpecificObjective:L.outcome||'', LearningOutcome:L.outcome||'', Warmup:L.warmup||'', Presentation:L.presentation||'', Preparation:L.preparation||'', Performance:L.performance||'', Assessment:L.assessment||'', Reflection:L.reflection||'', Homework:'', FormativeAssessment:'', TeacherComments:'' }; return {index:i+1, vars:tplVars}; }); }
async function exportThemePlannerDocFromState(S, filename='theme_planner_official.doc'){ const tpl=await loadThemeTpl(); const html = `<!DOCTYPE html><html><head><meta charset=\"utf-8\"><style>${tpl.css}</style></head><body>${fill(tpl.html, themeData(S))}</body></html>`; const a=document.createElement('a'); a.href=URL.createObjectURL(blobDoc(html)); a.download=filename; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href); a.remove();},500); }
async function exportThemePlannerPdfFromState(S, baseName='theme_planner_official'){ const tpl=await loadThemeTpl(); const html=`<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>${baseName}</title><style>${tpl.css}</style></head><body>${fill(tpl.html, themeData(S))}</body></html>`; const w=window.open('', '_blank'); w.document.open('text/html','replace'); w.document.write(html); w.document.close(); setTimeout(()=>{ w.print(); }, 300); }
async function exportLessonPlannerDocFromState(S, filename='lesson_planner_1_5_official.doc'){ const tpl=await loadLessonTpl(); const pages = lessonsHtmlFromState(S).map(page=>fill(tpl.html, page.vars)).join('<div style="page-break-after:always"></div>'); const html = `<!DOCTYPE html><html><head><meta charset=\"utf-8\"><style>${tpl.css}</style></head><body>${pages}</body></html>`; const a=document.createElement('a'); a.href=URL.createObjectURL(blobDoc(html)); a.download=filename; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href); a.remove();},500); }
async function exportLessonPlannerPdfFromState(S, baseName='lesson_planner_1_5_official'){ const tpl=await loadLessonTpl(); const pages=lessonsHtmlFromState(S).map(page=>fill(tpl.html, page.vars)).join('<div style="page-break-after:always"></div>'); const html=`<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>${baseName}</title><style>${tpl.css}</style></head><body>${pages}</body></html>`; const w=window.open('', '_blank'); w.document.open('text/html','replace'); w.document.write(html); w.document.close(); setTimeout(()=>{ w.print(); }, 300); }
